In [1]:
import numpy as np

1 Write a NumPy program to create an array of 10 zeros, array of 10 ones, and 
array of 10 fives. 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

2 Write a NumPy program to create an array of all even integers from 30 to 
70.

In [5]:
a=np.arange(30,71)
a[a%2==0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

3    Write a NumPy program to create an array of given shape (5,6) and integer 
    type, filled with zeros.

In [6]:
array = np.zeros((5, 6), dtype=int)
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

4 Create a 10x10 array with random values and find the minimum and 
maximum values.

In [7]:
array_10=np.random.rand(10, 10)
array_10

array([[0.59980587, 0.04840116, 0.07320322, 0.10577227, 0.04306463,
        0.77964251, 0.83966194, 0.78605981, 0.23609381, 0.58171533],
       [0.09169553, 0.81186   , 0.99831018, 0.977335  , 0.94167294,
        0.47721898, 0.44251435, 0.08339549, 0.52332114, 0.50702968],
       [0.00665667, 0.57685812, 0.13908917, 0.02221771, 0.30160242,
        0.00544564, 0.00534833, 0.06172264, 0.11765689, 0.28209771],
       [0.90619083, 0.94439943, 0.55451709, 0.75935739, 0.04903498,
        0.64827321, 0.96032131, 0.94591562, 0.48097887, 0.76295384],
       [0.92684612, 0.48334615, 0.7229765 , 0.5671911 , 0.1083535 ,
        0.94549116, 0.05745994, 0.88661775, 0.79321945, 0.37418753],
       [0.05553743, 0.49472555, 0.54318397, 0.27378101, 0.95612645,
        0.21194088, 0.28525098, 0.25391269, 0.6569042 , 0.94997111],
       [0.62387238, 0.12411108, 0.60422316, 0.43434462, 0.57124096,
        0.91125273, 0.38583918, 0.33241866, 0.60532103, 0.72981605],
       [0.02187749, 0.8689512 , 0.2489835

In [8]:
np.min(array_10)

0.00534832777737404

In [9]:
np.max(array_10)

0.9983101764220778

5 Write a NumPy program to create a 3x3 array with values ranging from 2 to 
10. 

In [10]:
np.arange(2,11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

6 Write a NumPy program to create an array of size = 20 using arrange, then 
extract all numbers from a given array greater than 15.


In [11]:
array_20 = np.arange(1, 21)
array_20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
x = array_20[array_20 > 15]
x

array([16, 17, 18, 19, 20])

7 Write a NumPy program to combine the two 2-dimensional arrays using 
hstack and vstack. 
Array 1: [[0, 1, 3], [5, 7, 9]] 
Array 2: [[0, 2, 4], [6, 8, 10]]

In [13]:
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

In [14]:
v=np.vstack((array1,array2))
v

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [15]:
h=np.hstack((array1,array2))
h

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

8 Write a NumPy program to create ones array of size 10 and change the 6th 
element to 11.

In [16]:
arr = np.ones(10, dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
arr[5] = 11
arr

array([ 1,  1,  1,  1,  1, 11,  1,  1,  1,  1])

9. Write a NumPy program to append a value to the end of an array. 


In [18]:
x=np.append(arr, [55,5])
x

array([ 1,  1,  1,  1,  1, 11,  1,  1,  1,  1, 55,  5])

10  Write a NumPy program to reverse an array [using two different methods]. 

In [19]:
x[::-1]

array([ 5, 55,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1])

In [20]:
np.flip(x)

array([ 5, 55,  1,  1,  1,  1, 11,  1,  1,  1,  1,  1])